apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shop-https-waf
  namespace: dpk-shop # Must equal to the namespace contains the Apache-PHP
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Force redirect HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: / 
    nginx.ingress.kubernetes.io/lua-resty-waf: "active" # Turn on WAF
    nginx.ingress.kubernetes.io/lua-resty-waf-ignore-rulesets: "41000_sqli"
    nginx.ingress.kubernetes.io/lua-resty-waf-score-threshold: "10"
spec:
  tls:
  - hosts: # Replace your domains in here
    - shop.thesis.analyticsvn.com
    secretName: tls-secret
  rules:
  - host: shop.thesis.analyticsvn.com # Replace your domain in here
    http:
      paths:
      - path: /
        backend:          
          serviceName: dpk-shop # Replace your service name
          servicePort: 80 # Replace your service port
