apiVersion: v1
kind: Service
metadata:
  name: dpk-shop # Name of Webserver Kubernetes service 
                 #- for routing and DNS
  namespace: dpk-shop
spec:
  ports:
  - port: 80 # Port of pod
  selector:
    app: php-apache
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: php-apache-deployment
  namespace: dpk-shop
spec:
  selector:
    matchLabels:
      app: php-apache
  serviceName: 'dpk-shop'
  replicas: 2 # Replicate to 2 pods for High Availability
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: webdevops
        image: webdevops/php-apache:5.6
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi          
        ports:
        - containerPort: 80
        volumeMounts:
          - name: azure-managed-disk # Must be equal to volumes:name (below)
            mountPath: '/app' # Path to Website location in Apache
      volumes:
        - name: azure-managed-disk 
          persistentVolumeClaim:
            claimName: azure-managed-disk # Must be equal to metadata:name 
                                    #in azure-disk-pvc.yaml
                                    
                                    