apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - dvwa.thesis.analyticsvn.com
  - netcore.thesis.analyticsvn.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dvwa.thesis.analyticsvn.com
      - netcore.thesis.analyticsvn.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer