apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dpk-shop-pvc
  namespace: dpk-shop
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile 
  # Must be equal to metadata:name in StorageClass in azure-file-storage
  resources:
    requests:
      storage: 20Gi # Maximum storage size for persistent volume