apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk # Name of the volume
  namespace: dpk-shop 
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium # Managed-Premium is SSD disk
  resources:
    requests:
      storage: 5Gi # Maximum size allocated
