apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: duc-phuong-khang-fpt@outlook.com # Replace with your real-email
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}